In [1]:
# Import Numpy Library
import numpy as np

1.Create a class Employee and then do the following
- • Create a data member to count the number of Employees
- • Create a constructor to initialize name, family, salary, department
- • Create a function to average salary
- • Create a Fulltime Employee class and it should inherit the properties of Employee class
- • Create the instances of Fulltime Employee class and Employee class and call their member functions.ions.

In [9]:
# created class Employee
class Employee():
    # create data members to keep count of employee count and list of salaries
    emp_count = 0
    
    # constructor to initilize the variables
    def __init__(self,name,family,salary,department):
        self.name = name,
        self.family = family,
        self.salary = salary,
        self.department = department,
        Employee.emp_count += 1
    
    # funtion to return average of salary
    def avg_salary(employees:list):
        # calculate salaries average
        salaries_list = [emp.salary[0] for emp in employees]
        # print(emp.salary[0] for emp in employees)
        avg_sal = sum(salaries_list)/Employee.emp_count     # method 1 : generic
        # avg_sal = np.mean(salaries_list)                      # method 2 : using numpy
        return avg_sal
    
# created FullTimeEmployee class and inherit the properties from Employee class
class FullTimeEmployee(Employee):
    def __init__(self,name,family,salary,department):
        # calling parent class constructor
        super().__init__(name,family,salary,department)

employees = []
employees.append(Employee("Naveen","Indluru",40000,"analytics"))
employees.append(Employee("Anvesh","Kalikiri",74000,"CTO"))

employees.append(FullTimeEmployee("Naveen Reddy","Indluru",50000,"data science"))
employees.append(FullTimeEmployee("Jagadeesh","Kethu",84000,"data analytics"))


print("using employee class",Employee.avg_salary(employees))
print("using fulltime employee class",FullTimeEmployee.avg_salary(employees))

using employee class 62000.0
using fulltime employee class 62000.0


2. Using NumPy create random vector of size 20 having only float in the range 1-20.

- Then reshape the array to 4 by 5
- Then replace the max in each row by 0 (axis=1)

(you can NOT implement it via for loop)

In [3]:
arr = np.random.uniform(1,20,20) # created a random vector of size 20 in the range of 1 - 20.
arr = arr.reshape(4,5) # reshaped the vector to array of (4,5) shape

In [4]:
# Task : replace the max in each row by 0 (axis = 1)

# print array before replacement
print("Array before :\n\n",arr,end="\n\n\n")

# get max elements of each row and reshape it 
each_row_max = np.max(arr,axis = 1).reshape(-1,1)

arr[arr == each_row_max] = 1

# print array after replacement
print("Array after replace the max element of each row with 1: \n\n", arr)

Array before :

 [[18.14317845  9.98967943  5.62396825 14.98742174 10.40461524]
 [11.37536677  1.23083579  8.83254936 12.15575555 14.80670628]
 [14.43273514 16.60053877 11.66523453 14.11921392 13.96043388]
 [13.29572942  9.40584639 10.23838828 18.15788719  2.28720703]]


Array after replace the max element of each row with 1: 

 [[ 1.          9.98967943  5.62396825 14.98742174 10.40461524]
 [11.37536677  1.23083579  8.83254936 12.15575555  1.        ]
 [14.43273514  1.         11.66523453 14.11921392 13.96043388]
 [13.29572942  9.40584639 10.23838828  1.          2.28720703]]
